[book]
title = "Firefox Data Documentation"

[build]
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.toc]
command = "mdbook-toc"

[output.html]
additional-css = ["dtmo.css", "mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/mozilla/firefox-data-docs"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
