[book]
title = "Mozilla Data Documentation"

[build]
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.toc]
command = "mdbook-toc"

[output.html]
mathjax-support = true
additional-css = ["dtmo.css", "mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/mozilla/data-docs"
git-branch = "main"
edit-url-template = "https://github.com/mozilla/data-docs/edit/main/{path}"
google-analytics = "UA-104326577-1"

[output.html.redirect]
"/concepts/analysis_intro.html" = "/introduction/what_data.html"
"/concepts/choosing_a_dataset.html" = "/cookbooks/bigquery/accessing_desktop_data.html"
"/concepts/getting_started.html" = "/introduction/index.html"
"/tools/interfaces.html" = "/introduction/tools.html"
"/datasets/mozetl/search_aggregates/reference.html" = "/datasets/search/search_aggregates/reference.html"
"/datasets/mozetl/search_clients_daily/reference.html" = "/datasets/search/search_clients_engines_sources_daily/reference.html"
"/datasets/search/search_clients_daily/reference.html" = "/datasets/search/search_clients_engines_sources_daily/reference.html"
"/datasets/mozetl/search_clients_last_seen/reference.html" = "/datasets/search/search_clients_last_seen/reference.html"
"/datasets/mozetl/client_ltv/reference.html" = "/datasets/search/client_ltv/reference.html"
"/cookbooks/bigquery-airflow.html" = "/cookbooks/scheduling_queries.html"
"/concepts/glean/accessing_glean_data.html" = "/cookbooks/accessing_glean_data.html"
"/concepts/choosing_a_dataset_mobile.html" = "/datasets/obsolete/legacy_mobile/reference.html"
"/datasets/other/attitudes_daily/reference.html" = "/datasets/obsolete/attitudes_daily/reference.html"
"/datasets/non_desktop/events_daily/reference.html" = "/datasets/bigquery/events_daily/reference.html"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
