[book]
title = "Mozilla Data Documentation"

[build]
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.toc]
command = "mdbook-toc"

[output.html]
mathjax-support = true
additional-css = ["dtmo.css", "mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/mozilla/data-docs"
google-analytics = "UA-104326577-1"

[output.html.redirect]
"/datasets/mozetl/search_aggregates/reference.html" = "/datasets/search/search_aggregates/reference.html"
"/datasets/mozetl/search_clients_daily/reference.html" = "/datasets/search/search_clients_daily/reference.html"
"/datasets/mozetl/search_clients_last_seen/reference.html" = "/datasets/search/search_clients_last_seen/reference.html"
"/datasets/mozetl/client_ltv/reference.html" = "/datasets/search/client_ltv/reference.html"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
