name: Deploy

on:
  push:
    branches:
      main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Install mdbook-dtmo
      run: |
        curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git badboy/mdbook-dtmo
        mdbook-dtmo --version

    - name: Build
      run: |
        mdbook-dtmo build .

    - name: Install github-pages
      run: |
        npm install gh-pages@3.1.0

    - name: Set Git config
      run: |
        git config user.email "no-one@mozilla.com"
        git config user.name "GitHub Actions docs-deploy job"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

    - name: Deploy to GitHub pages
      run: |
        echo "docs-origin.telemetry.mozilla.org" > book/CNAME
        npx gh-pages --dotfiles --message "Deploy docs" --dist book

